apiVersion: v1
kind: ConfigMap
metadata:
  name: env-configmap
data:
  OPENAI_ENGINE: davinci
  OPENAI_DEPLOYMENT_TYPE: Text
  OPENAI_EMBEDDINGS_ENGINE: text-embedding-ada-002
  OPENAI_EMBEDDINGS_ENGINE_DOC: text-embedding-ada-002
  OPENAI_EMBEDDINGS_ENGINE_QUERY: text-embedding-ada-002
  OPENAI_API_BASE: "https://cog-pfj4y3k2moyjw.openai.azure.com/"
  OPENAI_API_KEY: "[update to your key]"
  OPENAI_TEMPERATURE: "0.7"
  OPENAI_MAX_TOKENS: "-1"
  REDIS_ADDRESS: "[update to your address]"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: redis-stack-password
  BLOB_ACCOUNT_NAME: storage4openai
  BLOB_ACCOUNT_KEY: "[update to your key]"
  BLOB_ENDPOINT_SUFFIX: "core.windows.net"
  BLOB_CONTAINER_NAME: embedding
  QUEUE_NAME: doc-processing
  FORM_RECOGNIZER_ENDPOINT: "https://formreader.cognitiveservices.azure.cn/"
  FORM_RECOGNIZER_KEY: "[update to your key]"
  CHUNK_SIZE: "500"
  CHUNK_OVERLAP: "100"
  TRANSLATE_ENDPOINT: "https://api.translator.azure.cn/"
  TRANSLATE_KEY: "[update to your key]"
  TRANSLATE_REGION: chinanorth3
  VNET_DEPLOYMENT: "false"
  NUMBER_OF_EMBEDDINGS_FOR_QNA: "3"
  CONVERT_ADD_EMBEDDINGS_URL: "http://batch/api/BatchStartProcessing"
  AzureWebJobsStorage: "DefaultEndpointsProtocol=https;AccountName=storage4openai;AccountKey=[update to your key];EndpointSuffix=core.chinacloudapi.cn"
  QUESTION_PROMPT: "Please reply to the question using only the information present in the text above. If you can't find it, reply 'Not in the text'.\nQuestion: _QUESTION_\nAnswer:"
